/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewsCategory = IDL.Variant({
  'other' : IDL.Null,
  'characterReveal' : IDL.Null,
  'update' : IDL.Null,
  'newGame' : IDL.Null,
});
export const Time = IDL.Int;
export const NewsArticle = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'summary' : IDL.Text,
  'category' : NewsCategory,
});
export const HighScore = IDL.Record({
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
  'gameName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addHighScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'addNewsArticle' : IDL.Func([IDL.Text, IDL.Text, NewsCategory], [], []),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getHighScores' : IDL.Func([IDL.Text], [IDL.Vec(HighScore)], ['query']),
  'getNewsByCategory' : IDL.Func(
      [NewsCategory],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'removeHighScore' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeNewsArticle' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewsCategory = IDL.Variant({
    'other' : IDL.Null,
    'characterReveal' : IDL.Null,
    'update' : IDL.Null,
    'newGame' : IDL.Null,
  });
  const Time = IDL.Int;
  const NewsArticle = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'summary' : IDL.Text,
    'category' : NewsCategory,
  });
  const HighScore = IDL.Record({
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
    'gameName' : IDL.Text,
  });
  
  return IDL.Service({
    'addHighScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'addNewsArticle' : IDL.Func([IDL.Text, IDL.Text, NewsCategory], [], []),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getHighScores' : IDL.Func([IDL.Text], [IDL.Vec(HighScore)], ['query']),
    'getNewsByCategory' : IDL.Func(
        [NewsCategory],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'removeHighScore' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeNewsArticle' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };