/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HighScore {
  'score' : bigint,
  'playerName' : string,
  'gameName' : string,
}
export interface NewsArticle {
  'title' : string,
  'date' : Time,
  'summary' : string,
  'category' : NewsCategory,
}
export type NewsCategory = { 'other' : null } |
  { 'characterReveal' : null } |
  { 'update' : null } |
  { 'newGame' : null };
export type Time = bigint;
export interface _SERVICE {
  'addHighScore' : ActorMethod<[string, string, bigint], undefined>,
  'addNewsArticle' : ActorMethod<[string, string, NewsCategory], undefined>,
  'getAllNews' : ActorMethod<[], Array<NewsArticle>>,
  'getHighScores' : ActorMethod<[string], Array<HighScore>>,
  'getNewsByCategory' : ActorMethod<[NewsCategory], Array<NewsArticle>>,
  'removeHighScore' : ActorMethod<[string, string], undefined>,
  'removeNewsArticle' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];